theme: jekyll-theme-midnight
title: "SAAKD Productivity Corp."
description: "A blog made by Safin, Alex, Amay, Kaiden, and David."
gitorg: "https://github.com/DavidVasilev1/leuck-copy"
description: "Be Productive"
google_analytics:
repository: DavidVasilev1/leuck-copy