theme: jekyll-theme-midnight
title: "Group SAAKD"
description: "A blog made by Safin, Alex, Amay, Kaiden, and David."
gitorg: "https://github.com/DavidVasilev1/leuck-copy"
description: "Modified Site"
google_analytics:
